[healthy-27-node-SAP-cluster]

directories = ["./test/fixtures/scenarios/healthy-27-node-SAP-cluster"]

[single-hana-single-app]

directories = ["./test/fixtures/scenarios/single-hana-single-app"]

[hana-scale-out]

directories = ["./test/fixtures/scenarios/hana-scale-out"]

[hana-diskless-sbd]

directories = ["./test/fixtures/scenarios/hana-diskless-sbd"]

[hana-scale-up-angi]

directories = ["./test/fixtures/scenarios/hana-scale-up-angi"]

[aws-landscape]

directories = ["./test/fixtures/scenarios/aws-landscape"]

[gcp-landscape]

directories = ["./test/fixtures/scenarios/gcp-landscape"]

[multi-tenant]

directories = ["./test/fixtures/scenarios/multi-tenant"]

[sap-system-detail-GRAY]

files = [
    "./test/fixtures/scenarios/sap-system-details/1b0e9297-97dd-55d6-9874-8efde4d84c90_sap_system_discovery_GRAY.json",
]

[sap-system-detail-GREEN]

files = [
    "./test/fixtures/scenarios/sap-system-details/1b0e9297-97dd-55d6-9874-8efde4d84c90_sap_system_discovery_GREEN.json",
]

[sap-system-detail-YELLOW]

files = [
    "./test/fixtures/scenarios/sap-system-details/1b0e9297-97dd-55d6-9874-8efde4d84c90_sap_system_discovery_YELLOW.json",
]

[sap-system-detail-RED]

files = [
    "./test/fixtures/scenarios/sap-system-details/1b0e9297-97dd-55d6-9874-8efde4d84c90_sap_system_discovery_RED.json",
]

[sap-system-detail-NEW]

files = [
    "./test/fixtures/scenarios/sap-system-details/1b0e9297-97dd-55d6-9874-8efde4d84c90_sap_system_discovery_new.json",
]

[hana-database-detail-GRAY]

files = [
    "./test/fixtures/scenarios/hana-database-details/0a055c90-4cb6-54ce-ac9c-ae3fedaf40d4_sap_system_discovery_GRAY.json",
]

[hana-database-detail-GREEN]

files = [
    "./test/fixtures/scenarios/hana-database-details/0a055c90-4cb6-54ce-ac9c-ae3fedaf40d4_sap_system_discovery_GREEN.json",
]

[hana-database-detail-YELLOW]

files = [
    "./test/fixtures/scenarios/hana-database-details/0a055c90-4cb6-54ce-ac9c-ae3fedaf40d4_sap_system_discovery_YELLOW.json",
]

[hana-database-detail-RED]

files = [
    "./test/fixtures/scenarios/hana-database-details/0a055c90-4cb6-54ce-ac9c-ae3fedaf40d4_sap_system_discovery_RED.json",
]

[hana-database-detail-NEW]

files = [
    "./test/fixtures/scenarios/hana-database-details/0a055c90-4cb6-54ce-ac9c-ae3fedaf40d4_sap_system_discovery_new.json",
]

[sap-systems-overview-GREEN]

files = [
    "./test/fixtures/scenarios//healthy-27-node-SAP-cluster/7269ee51-5007-5849-aaa7-7c4a98b0c9ce_sap_system_discovery.json",
]

[sap-systems-overview-GRAY]

files = [
    "./test/fixtures/scenarios/sap-systems-overview/fb2c6b8a-9915-5969-a6b7-8b5a42de1971_sap_system_discovery_GRAY.json",
]

[sap-systems-overview-YELLOW]

files = [
    "./test/fixtures/scenarios/sap-systems-overview/9a3ec76a-dd4f-5013-9cf0-5eb4cf89898f_sap_system_discovery_YELLOW.json",
]

[sap-systems-overview-RED]

files = [
    "./test/fixtures/scenarios/sap-systems-overview/1b0e9297-97dd-55d6-9874-8efde4d84c90_sap_system_discovery_RED.json",
]

[sap-systems-overview-hana-RED]

files = [
    "./test/fixtures/scenarios/sap-systems-overview/13e8c25c-3180-5a9a-95c8-51ec38e50cfc_sap_system_discovery_RED.json",
]

[sap-systems-overview-DAA]

files = [
    "./test/fixtures/scenarios/sap-systems-overview/2ace860d-38e9-55f4-b051-faf4336e71d6_sap_system_discovery_DAA.json",
]

[sap-systems-overview-NWD-00-present]

files = [
    "./test/fixtures/scenarios/healthy-27-node-SAP-cluster/7269ee51-5007-5849-aaa7-7c4a98b0c9ce_sap_system_discovery.json",
]

[sap-systems-overview-NWD-00-absent]

files = [
    "./test/fixtures/scenarios/sap-systems-overview/7269ee51-5007-5849-aaa7-7c4a98b0c9ce_sap_system_discovery_absent.json",
]

[sap-systems-overview-NWD-01-present]

files = [
    "./test/fixtures/scenarios/healthy-27-node-SAP-cluster/9a3ec76a-dd4f-5013-9cf0-5eb4cf89898f_sap_system_discovery.json",
]

[sap-systems-overview-NWD-01-absent]

files = [
    "./test/fixtures/scenarios/sap-systems-overview/9a3ec76a-dd4f-5013-9cf0-5eb4cf89898f_sap_system_discovery_absent.json",
]

[sap-systems-overview-HDD-10-present]

files = [
    "./test/fixtures/scenarios/healthy-27-node-SAP-cluster/13e8c25c-3180-5a9a-95c8-51ec38e50cfc_sap_system_discovery.json",
]

[sap-systems-overview-HDD-10-absent]

files = [
    "./test/fixtures/scenarios/sap-systems-overview/13e8c25c-3180-5a9a-95c8-51ec38e50cfc_sap_system_discovery_absent.json",
]

[cluster-4-SOK]

files = [
    "./test/fixtures/scenarios/clusters-overview/13e8c25c-3180-5a9a-95c8-51ec38e50cfc_ha_cluster_discovery_4_SOK.json",
]

[cluster-1-SOK]

files = [
    "./test/fixtures/scenarios/clusters-overview/13e8c25c-3180-5a9a-95c8-51ec38e50cfc_ha_cluster_discovery_1_SOK.json",
]

[cluster-4-SFAIL]

files = [
    "./test/fixtures/scenarios/clusters-overview/13e8c25c-3180-5a9a-95c8-51ec38e50cfc_ha_cluster_discovery_4_SFAIL.json",
]

[cluster-1-SFAIL]

files = [
    "./test/fixtures/scenarios/clusters-overview/13e8c25c-3180-5a9a-95c8-51ec38e50cfc_ha_cluster_discovery_1_SFAIL.json",
]

[cluster-unnamed]

files = [
    "./test/fixtures/scenarios/clusters-overview/13e8c25c-3180-5a9a-95c8-51ec38e50cfc_ha_cluster_discovery_unnamed.json",
]

[cluster-unknown-provider]

files = [
    "./test/fixtures/scenarios/hana-cluster-details/b767b3e9-e802-587e-a442-541d093b86b9_ha_cluster_discovery_unknown_provider.json",
]

[cluster-kvm-provider]

files = [
    "./test/fixtures/scenarios/hana-cluster-details/b767b3e9-e802-587e-a442-541d093b86b9_ha_cluster_discovery_kvm_provider.json",
]

[cluster-vmware-provider]

files = [
    "./test/fixtures/scenarios/hana-cluster-details/b767b3e9-e802-587e-a442-541d093b86b9_ha_cluster_discovery_vmware_provider.json",
]

[cluster-nutanix-provider]

files = [
    "./test/fixtures/scenarios/hana-cluster-details/b767b3e9-e802-587e-a442-541d093b86b9_ha_cluster_discovery_nutanix_provider.json",
]

[host-details-vmhdbprd01]

files = [
    "./test/fixtures/scenarios/healthy-27-node-SAP-cluster/9cd46919-5f19-59aa-993e-cf3736c71053_host_discovery.json",
]

[host-details-azure]

files = [
    "./test/fixtures/scenarios/healthy-27-node-SAP-cluster/9cd46919-5f19-59aa-993e-cf3736c71053_cloud_discovery.json",
]

[host-details-aws]

files = [
    "./test/fixtures/scenarios/host-details/9cd46919-5f19-59aa-993e-cf3736c71053_cloud_discovery_aws.json",
]

[host-details-gcp]

files = [
    "./test/fixtures/scenarios/host-details/9cd46919-5f19-59aa-993e-cf3736c71053_cloud_discovery_gcp.json",
]

[host-details-kvm]

files = [
    "./test/fixtures/scenarios/host-details/9cd46919-5f19-59aa-993e-cf3736c71053_cloud_discovery_kvm.json",
]

[host-details-vmware]

files = [
    "./test/fixtures/scenarios/host-details/9cd46919-5f19-59aa-993e-cf3736c71053_cloud_discovery_vmware.json",
]

[host-details-nutanix]

files = [
    "./test/fixtures/scenarios/host-details/9cd46919-5f19-59aa-993e-cf3736c71053_cloud_discovery_nutanix.json",
]

[host-details-unknown]

files = [
    "./test/fixtures/scenarios/host-details/9cd46919-5f19-59aa-993e-cf3736c71053_cloud_discovery_unknown.json",
]

[host-vmhdbdev01-restore]

files = [
    "./test/fixtures/scenarios/healthy-27-node-SAP-cluster/13e8c25c-3180-5a9a-95c8-51ec38e50cfc_host_discovery.json",
    "./test/fixtures/scenarios/healthy-27-node-SAP-cluster/13e8c25c-3180-5a9a-95c8-51ec38e50cfc_subscription_discovery.json",
    "./test/fixtures/scenarios/healthy-27-node-SAP-cluster/13e8c25c-3180-5a9a-95c8-51ec38e50cfc_cloud_discovery.json",
    "./test/fixtures/scenarios/healthy-27-node-SAP-cluster/13e8c25c-3180-5a9a-95c8-51ec38e50cfc_ha_cluster_discovery.json",
    "./test/fixtures/scenarios/healthy-27-node-SAP-cluster/13e8c25c-3180-5a9a-95c8-51ec38e50cfc_sap_system_discovery.json"
]

[host-vmhdbprd02-restore]

files = [
    "./test/fixtures/scenarios/healthy-27-node-SAP-cluster/b767b3e9-e802-587e-a442-541d093b86b9_host_discovery.json",
    "./test/fixtures/scenarios/healthy-27-node-SAP-cluster/b767b3e9-e802-587e-a442-541d093b86b9_subscription_discovery.json",
    "./test/fixtures/scenarios/healthy-27-node-SAP-cluster/b767b3e9-e802-587e-a442-541d093b86b9_cloud_discovery.json",
    "./test/fixtures/scenarios/healthy-27-node-SAP-cluster/b767b3e9-e802-587e-a442-541d093b86b9_ha_cluster_discovery.json",
    "./test/fixtures/scenarios/healthy-27-node-SAP-cluster/b767b3e9-e802-587e-a442-541d093b86b9_sap_system_discovery.json"
]

[host-vmnwdev02-restore]

files = [
    "./test/fixtures/scenarios/healthy-27-node-SAP-cluster/fb2c6b8a-9915-5969-a6b7-8b5a42de1971_host_discovery.json",
    "./test/fixtures/scenarios/healthy-27-node-SAP-cluster/fb2c6b8a-9915-5969-a6b7-8b5a42de1971_subscription_discovery.json",
    "./test/fixtures/scenarios/healthy-27-node-SAP-cluster/fb2c6b8a-9915-5969-a6b7-8b5a42de1971_cloud_discovery.json",
    "./test/fixtures/scenarios/healthy-27-node-SAP-cluster/fb2c6b8a-9915-5969-a6b7-8b5a42de1971_ha_cluster_discovery.json",
    "./test/fixtures/scenarios/healthy-27-node-SAP-cluster/fb2c6b8a-9915-5969-a6b7-8b5a42de1971_sap_system_discovery.json"
]

[host-vmhdbdev02-restore]

files = [
    "./test/fixtures/scenarios/healthy-27-node-SAP-cluster/0a055c90-4cb6-54ce-ac9c-ae3fedaf40d4_host_discovery.json",
    "./test/fixtures/scenarios/healthy-27-node-SAP-cluster/0a055c90-4cb6-54ce-ac9c-ae3fedaf40d4_subscription_discovery.json",
    "./test/fixtures/scenarios/healthy-27-node-SAP-cluster/0a055c90-4cb6-54ce-ac9c-ae3fedaf40d4_cloud_discovery.json",
    "./test/fixtures/scenarios/healthy-27-node-SAP-cluster/0a055c90-4cb6-54ce-ac9c-ae3fedaf40d4_ha_cluster_discovery.json",
    "./test/fixtures/scenarios/healthy-27-node-SAP-cluster/0a055c90-4cb6-54ce-ac9c-ae3fedaf40d4_sap_system_discovery.json" 
]

[host-vmhdbqas01-restore]

files = [
    "./test/fixtures/scenarios/healthy-27-node-SAP-cluster/99cf8a3a-48d6-57a4-b302-6e4482227ab6_host_discovery.json",
    "./test/fixtures/scenarios/healthy-27-node-SAP-cluster/99cf8a3a-48d6-57a4-b302-6e4482227ab6_subscription_discovery.json",
    "./test/fixtures/scenarios/healthy-27-node-SAP-cluster/99cf8a3a-48d6-57a4-b302-6e4482227ab6_cloud_discovery.json",
    "./test/fixtures/scenarios/healthy-27-node-SAP-cluster/99cf8a3a-48d6-57a4-b302-6e4482227ab6_ha_cluster_discovery.json",
    "./test/fixtures/scenarios/healthy-27-node-SAP-cluster/99cf8a3a-48d6-57a4-b302-6e4482227ab6_sap_system_discovery.json" 
]

[host-vmdrbddev01-saptune-uninstalled]

files = [
    "./test/fixtures/scenarios/hosts-overview/240f96b1-8d26-53b7-9e99-ffb0f2e735bf_saptune_discovery_uninstalled.json"
]

[host-vmdrbddev01-saptune-not-tuned]

files = [
    "./test/fixtures/scenarios/hosts-overview/240f96b1-8d26-53b7-9e99-ffb0f2e735bf_saptune_discovery_not_tuned.json"
]

[host-vmhdbprd01-saptune-uninstalled]

files = [
    "./test/fixtures/scenarios/hosts-overview/9cd46919-5f19-59aa-993e-cf3736c71053_saptune_discovery_uninstalled.json"
]

[host-vmhdbprd01-saptune-unsupported]

files = [
    "./test/fixtures/scenarios/hosts-overview/9cd46919-5f19-59aa-993e-cf3736c71053_saptune_discovery_unsupported.json"
]

[host-vmhdbprd01-saptune-not-compliant]

files = [
    "./test/fixtures/scenarios/hosts-overview/9cd46919-5f19-59aa-993e-cf3736c71053_saptune_discovery_not_compliant.json"
]

[host-vmhdbprd01-saptune-not-tuned]

files = [
    "./test/fixtures/scenarios/hosts-overview/9cd46919-5f19-59aa-993e-cf3736c71053_saptune_discovery_not_tuned.json"
]

[host-vmhdbprd01-saptune-compliant]

files = [
    "./test/fixtures/scenarios/hosts-overview/9cd46919-5f19-59aa-993e-cf3736c71053_saptune_discovery_compliant.json"
]

[host-vmhdbprd01-saptune-service-status-passing]

files = [
    "./test/fixtures/scenarios/hosts-overview/9cd46919-5f19-59aa-993e-cf3736c71053_saptune_discovery_saptune_service_status_passing.json"
    ]

[sapsystem-NWD-restore]

files = [
    "./test/fixtures/scenarios/healthy-27-node-SAP-cluster/7269ee51-5007-5849-aaa7-7c4a98b0c9ce_cloud_discovery.json",
    "./test/fixtures/scenarios/healthy-27-node-SAP-cluster/7269ee51-5007-5849-aaa7-7c4a98b0c9ce_ha_cluster_discovery.json",
    "./test/fixtures/scenarios/healthy-27-node-SAP-cluster/7269ee51-5007-5849-aaa7-7c4a98b0c9ce_host_discovery.json",
    "./test/fixtures/scenarios/healthy-27-node-SAP-cluster/7269ee51-5007-5849-aaa7-7c4a98b0c9ce_sap_system_discovery.json",
    "./test/fixtures/scenarios/healthy-27-node-SAP-cluster/7269ee51-5007-5849-aaa7-7c4a98b0c9ce_subscription_discovery.json",
    "./test/fixtures/scenarios/healthy-27-node-SAP-cluster/fb2c6b8a-9915-5969-a6b7-8b5a42de1971_cloud_discovery.json",
    "./test/fixtures/scenarios/healthy-27-node-SAP-cluster/fb2c6b8a-9915-5969-a6b7-8b5a42de1971_ha_cluster_discovery.json",
    "./test/fixtures/scenarios/healthy-27-node-SAP-cluster/fb2c6b8a-9915-5969-a6b7-8b5a42de1971_host_discovery.json",
    "./test/fixtures/scenarios/healthy-27-node-SAP-cluster/fb2c6b8a-9915-5969-a6b7-8b5a42de1971_sap_system_discovery.json",
    "./test/fixtures/scenarios/healthy-27-node-SAP-cluster/fb2c6b8a-9915-5969-a6b7-8b5a42de1971_subscription_discovery.json",
    "./test/fixtures/scenarios/healthy-27-node-SAP-cluster/9a3ec76a-dd4f-5013-9cf0-5eb4cf89898f_cloud_discovery.json",
    "./test/fixtures/scenarios/healthy-27-node-SAP-cluster/9a3ec76a-dd4f-5013-9cf0-5eb4cf89898f_ha_cluster_discovery.json",
    "./test/fixtures/scenarios/healthy-27-node-SAP-cluster/9a3ec76a-dd4f-5013-9cf0-5eb4cf89898f_host_discovery.json",
    "./test/fixtures/scenarios/healthy-27-node-SAP-cluster/9a3ec76a-dd4f-5013-9cf0-5eb4cf89898f_sap_system_discovery.json",
    "./test/fixtures/scenarios/healthy-27-node-SAP-cluster/9a3ec76a-dd4f-5013-9cf0-5eb4cf89898f_subscription_discovery.json",
    "./test/fixtures/scenarios/healthy-27-node-SAP-cluster/1b0e9297-97dd-55d6-9874-8efde4d84c90_cloud_discovery.json",
    "./test/fixtures/scenarios/healthy-27-node-SAP-cluster/1b0e9297-97dd-55d6-9874-8efde4d84c90_ha_cluster_discovery.json",
    "./test/fixtures/scenarios/healthy-27-node-SAP-cluster/1b0e9297-97dd-55d6-9874-8efde4d84c90_host_discovery.json",
    "./test/fixtures/scenarios/healthy-27-node-SAP-cluster/1b0e9297-97dd-55d6-9874-8efde4d84c90_sap_system_discovery.json",
    "./test/fixtures/scenarios/healthy-27-node-SAP-cluster/1b0e9297-97dd-55d6-9874-8efde4d84c90_subscription_discovery.json",
]

[cluster-hana_cluster_1-restore]

files = [
    "./test/fixtures/scenarios/healthy-27-node-SAP-cluster/13e8c25c-3180-5a9a-95c8-51ec38e50cfc_cloud_discovery.json",
    "./test/fixtures/scenarios/healthy-27-node-SAP-cluster/13e8c25c-3180-5a9a-95c8-51ec38e50cfc_ha_cluster_discovery.json",
    "./test/fixtures/scenarios/healthy-27-node-SAP-cluster/13e8c25c-3180-5a9a-95c8-51ec38e50cfc_host_discovery.json",
    "./test/fixtures/scenarios/healthy-27-node-SAP-cluster/13e8c25c-3180-5a9a-95c8-51ec38e50cfc_sap_system_discovery.json",
    "./test/fixtures/scenarios/healthy-27-node-SAP-cluster/13e8c25c-3180-5a9a-95c8-51ec38e50cfc_subscription_discovery.json",
    "./test/fixtures/scenarios/healthy-27-node-SAP-cluster/0a055c90-4cb6-54ce-ac9c-ae3fedaf40d4_cloud_discovery.json",
    "./test/fixtures/scenarios/healthy-27-node-SAP-cluster/0a055c90-4cb6-54ce-ac9c-ae3fedaf40d4_ha_cluster_discovery.json",
    "./test/fixtures/scenarios/healthy-27-node-SAP-cluster/0a055c90-4cb6-54ce-ac9c-ae3fedaf40d4_host_discovery.json",
    "./test/fixtures/scenarios/healthy-27-node-SAP-cluster/0a055c90-4cb6-54ce-ac9c-ae3fedaf40d4_sap_system_discovery.json",
    "./test/fixtures/scenarios/healthy-27-node-SAP-cluster/0a055c90-4cb6-54ce-ac9c-ae3fedaf40d4_subscription_discovery.json",    
]

[sap-systems-overview-moved]

files = [
    "./test/fixtures/scenarios/sap-systems-overview/fb2c6b8a-9915-5969-a6b7-8b5a42de1971_sap_system_discovery_MOVED.json"
]

[sap-systems-overview-revert-moved]

files = [
    "./test/fixtures/scenarios/healthy-27-node-SAP-cluster/7269ee51-5007-5849-aaa7-7c4a98b0c9ce_sap_system_discovery.json"
]

[sap-systems-overview-not-moved]

files = [
    "./test/fixtures/scenarios/sap-systems-overview/9a3ec76a-dd4f-5013-9cf0-5eb4cf89898f_sap_system_discovery_NOT_MOVED.json"
]

[sap-systems-overview-revert-not-moved]

files = [
    "./test/fixtures/scenarios/healthy-27-node-SAP-cluster/9a3ec76a-dd4f-5013-9cf0-5eb4cf89898f_sap_system_discovery.json"
]